# NAME: Richard Khillah
# EMAIL: rkhillah@test.net
# ID: 12345678

.SILENT:

default: 
	gcc -Wall -Wextra -o lab1a lab1a.c
clean:
	rm -f lab1a *.tar.gz
dist:
	tar -cvzf lab1a-12345678.tar.gz lab1a.c Makefile README
