# NAME: Richard Khillah
# EMAIL: rkhillah@test.net
# ID: 1

.SILENT:

default: 
	gcc -Wall -Wextra -o lab1a lab1a.c
clean:
	rm -f lab1a lab1a-1.tar.gz
dist:
	tar -czf lab1a-1.tar.gz lab1a.c Makefile README
